#!/usr/bin/env pwsh
# azd postprovision hook (Windows / pwsh).
#
# Runs automatically after `azd provision`. It provisions the Azure AI Foundry
# Memory Store the agent uses and stores MEMORY_STORE_NAME so the agent can
# reach it — collapsing the manual provisioning step into a single `azd provision`.
#
# Wire it up by adding this to the azure.yaml generated by `azd ai agent init`:
#
#   hooks:
#     postprovision:
#       posix:
#         shell: sh
#         run: ./src/<agent-name>/hooks/postprovision.sh
#       windows:
#         shell: pwsh
#         run: ./src/<agent-name>/hooks/postprovision.ps1

$ErrorActionPreference = "Stop"

# PowerShell does not stop on a non-zero exit code from a native command (like
# azd), so check $LASTEXITCODE after each azd call and fail loudly.
function Invoke-Checked {
    param([scriptblock] $Script, [string] $What)
    & $Script
    if ($LASTEXITCODE -ne 0) { throw "$What failed (exit $LASTEXITCODE)." }
}

# Run from the sample directory (the parent of hooks/) so provision_memory_store.py
# resolves no matter which directory azd invokes the hook from.
Set-Location (Split-Path -Parent $PSScriptRoot)

# The memory store needs an embedding model deployment; it isn't part of the
# agent's own model resources, so it's a prerequisite you set once.
if (-not $env:AZURE_AI_EMBEDDING_MODEL_DEPLOYMENT_NAME) {
    throw "AZURE_AI_EMBEDDING_MODEL_DEPLOYMENT_NAME is not set. Run: azd env set AZURE_AI_EMBEDDING_MODEL_DEPLOYMENT_NAME ""text-embedding-3-small"""
}

# Default the memory store name and persist it so the agent (which reads
# MEMORY_STORE_NAME at deploy time) and the provisioning script agree.
if (-not $env:MEMORY_STORE_NAME) {
    $env:MEMORY_STORE_NAME = "agent_framework_memory"
    Invoke-Checked { azd env set MEMORY_STORE_NAME $env:MEMORY_STORE_NAME } "env set MEMORY_STORE_NAME"
}

Write-Host "Provisioning the Foundry Memory Store '$($env:MEMORY_STORE_NAME)'..."
# provision_memory_store.py uses the async azure-ai-projects client, which needs
# aiohttp as its transport. Install the narrow set the script imports.
Invoke-Checked { python -m pip install -q azure-ai-projects azure-identity aiohttp python-dotenv } "pip install"
# Idempotent: leaves an existing store with the same name untouched.
Invoke-Checked { python provision_memory_store.py } "provision_memory_store.py"

# `azd ai agent init` resolves ${MEMORY_STORE_NAME} in agent.yaml at init time —
# before this hook runs and sets the value — so the manifest is left with an empty
# value and `azd deploy` would ship MEMORY_STORE_NAME="" to the container, leaving
# the agent with no store to read or write. Write the resolved name into agent.yaml
# so the deployed agent gets it. Idempotent.
$manifest = Join-Path (Get-Location) "agent.yaml"
if (Test-Path $manifest) {
    $content = [System.IO.File]::ReadAllText($manifest)
    $pattern = '(?m)(^[ \t]*-[ \t]*name:[ \t]*MEMORY_STORE_NAME[ \t]*\r?\n[ \t]*value:[ \t]*).*$'
    $updated = [System.Text.RegularExpressions.Regex]::Replace($content, $pattern, ('${1}' + $env:MEMORY_STORE_NAME))
    if ($updated -ne $content) {
        [System.IO.File]::WriteAllText($manifest, $updated)
        Write-Host "Set MEMORY_STORE_NAME in agent.yaml to '$($env:MEMORY_STORE_NAME)' for deploy."
    }
}

Write-Host "Done. MEMORY_STORE_NAME = $($env:MEMORY_STORE_NAME)"
