#!/usr/bin/env sh
# azd postprovision hook (POSIX / sh).
#
# Runs automatically after `azd provision`. It provisions the Azure AI Foundry
# Memory Store the agent uses and stores MEMORY_STORE_NAME so the agent can
# reach it — collapsing the manual provisioning step into a single `azd provision`.
#
# Wire it up by adding this to the azure.yaml generated by `azd ai agent init`:
#
#   hooks:
#     postprovision:
#       posix:
#         shell: sh
#         run: ./src/<agent-name>/hooks/postprovision.sh
#       windows:
#         shell: pwsh
#         run: ./src/<agent-name>/hooks/postprovision.ps1

set -e

# Run from the sample directory (the parent of hooks/) so provision_memory_store.py
# resolves no matter which directory azd invokes the hook from.
cd "$(CDPATH= cd "$(dirname "$0")/.." && pwd)"

# The memory store needs an embedding model deployment; it isn't part of the
# agent's own model resources, so it's a prerequisite you set once.
if [ -z "$AZURE_AI_EMBEDDING_MODEL_DEPLOYMENT_NAME" ]; then
  echo "AZURE_AI_EMBEDDING_MODEL_DEPLOYMENT_NAME is not set. Run: azd env set AZURE_AI_EMBEDDING_MODEL_DEPLOYMENT_NAME \"text-embedding-3-small\"" >&2
  exit 1
fi

# Default the memory store name and persist it so the agent (which reads
# MEMORY_STORE_NAME at deploy time) and the provisioning script agree.
if [ -z "$MEMORY_STORE_NAME" ]; then
  MEMORY_STORE_NAME="agent_framework_memory"
  export MEMORY_STORE_NAME
  azd env set MEMORY_STORE_NAME "$MEMORY_STORE_NAME"
fi

echo "Provisioning the Foundry Memory Store '$MEMORY_STORE_NAME'..."
# provision_memory_store.py uses the async azure-ai-projects client, which needs
# aiohttp as its transport. Install the narrow set the script imports.
python -m pip install -q azure-ai-projects azure-identity aiohttp python-dotenv
# Idempotent: leaves an existing store with the same name untouched.
python provision_memory_store.py

# `azd ai agent init` resolves ${MEMORY_STORE_NAME} in agent.yaml at init time —
# before this hook runs and sets the value — so the manifest is left with an empty
# value and `azd deploy` would ship MEMORY_STORE_NAME="" to the container, leaving
# the agent with no store to read or write. Write the resolved name into agent.yaml
# so the deployed agent gets it. Idempotent.
if [ -f agent.yaml ]; then
  awk -v val="$MEMORY_STORE_NAME" '
    prev ~ /name:[[:space:]]*MEMORY_STORE_NAME[[:space:]]*$/ && /value:/ {
      sub(/value:.*/, "value: " val)
    }
    { print; prev = $0 }
  ' agent.yaml > agent.yaml.tmp && mv agent.yaml.tmp agent.yaml
  echo "Set MEMORY_STORE_NAME in agent.yaml to '$MEMORY_STORE_NAME' for deploy."
fi

echo "Done. MEMORY_STORE_NAME = $MEMORY_STORE_NAME"
